# Generated by Django 5.1 on 2025-01-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimages',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.review'),
        ),
        migrations.AlterField(
            model_name='reviewimages',
            name='review_image_path',
            field=models.ImageField(upload_to='review_images/'),
        ),
    ]
