# Generated by Django 5.1 on 2024-12-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
