# Generated by Django 5.1 on 2024-12-27 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.foods')),
            ],
            options={
                'db_table': 'food_categories',
            },
        ),
    ]
