# Generated by Django 5.1 on 2025-01-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.foodcategory'),
        ),
        migrations.AlterModelTable(
            name='foodcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='foodstore',
            table='food_categories',
        ),
    ]
