# Generated by Django 5.1 on 2025-01-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='kind',
            field=models.CharField(max_length=30),
        ),
    ]
