# Generated by Django 5.1 on 2025-03-24 05:07

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
