# Generated by Django 5.1 on 2025-03-24 05:07

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'app/fixture/app_data', app_label='app')

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_store_area_alter_store_latitude_and_more'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
