# Generated by Django 5.1 on 2025-03-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_store_area_alter_store_latitude_and_more'),
        ('app', '0013_auto_20250324_1407'),
    ]

    operations = [
    ]
