# Generated by Django 5.1 on 2025-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20250326_1449'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'food')},
        ),
    ]
